# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e05d7caa57526fd789c4b499d3263d4ac663b7aefe2187a7def0a26ca86db1bcb84c9e4657ce6d2e90cea1cc6eb7a5a7935654a30633363d54618adff07ee37

test:
  secret_key_base: 3eb0a98be6c7674ef73da3f4c365e6637d26ae119f9fa614315c43cca2585e5033dc677904bb46b5e329f1b057c285df739926d5b00140bce5061bab0416fde8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
